@coreBaseUrl = http://localhost:3001
@bridgeBaseUrl = http://localhost:3002
@username = REPLACE_USERNAME
@password = REPLACE_PASSWORD

### 1) Login ke Core API
# @name coreLogin
POST {{coreBaseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### 2) Ambil products dari Bridge API dengan token login Core
GET {{bridgeBaseUrl}}/products
Authorization: Bearer {{coreLogin.response.body.token}}
